name: demo
description: Demo of Flutter, Bloc, Cubit, Organization, and HTTP

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  path_provider: ^2.0.11
  cached_network_image: ^3.2.2
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true